### ISSUE TITLE
Some strange entries in my dedicated server log

### ISSUE THREAD

**Issue by vico93** [ReviversMC/modern-glass-doors#19]
I'm testing my modpack (that includes v5.1.0 of this mod), and i noticed when booting for the second time that there a lot of entry errors  related to this mod items on Fabric and [Load my 🤬 Tags](https://github.com/Dragon-Seeker/LoadMyFuckingTags) mod, and i'm afraid it could break at some point.

Some examples of errors are the following:
```
[19:22:13] [Worker-Main-2/ERROR]: [Load My Fucking Tags] Couldn't load certain entries with the tag minecraft:non_flammable_wood: modern_glass_doors:crimson_glass_door (from fabric), modern_glass_doors:warped_glass_door (from fabric), modern_glass_doors:crimson_glass_trapdoor (from fabric), modern_glass_doors:warped_glass_trapdoor (from fabric)
[19:22:13] [Worker-Main-1/ERROR]: [Load My Fucking Tags] Couldn't load certain entries with the tag modern_glass_doors:wooden_glass_trapdoors: modern_glass_doors:oak_glass_trapdoor (from fabric), modern_glass_doors:spruce_glass_trapdoor (from fabric), modern_glass_doors:birch_glass_trapdoor (from fabric), modern_glass_doors:acacia_glass_trapdoor (from fabric), modern_glass_doors:jungle_glass_trapdoor (from fabric), modern_glass_doors:dark_oak_glass_trapdoor (from fabric), modern_glass_doors:crimson_glass_trapdoor (from fabric), modern_glass_doors:warped_glass_trapdoor (from fabric), modern_glass_doors:mangrove_glass_trapdoor (from fabric), modern_glass_doors:bamboo_glass_trapdoor (from fabric), modern_glass_doors:cherry_glass_trapdoor (from fabric)
[19:22:13] [Worker-Main-1/ERROR]: [Load My Fucking Tags] Couldn't load certain entries with the tag modern_glass_doors:wooden_glass_doors: modern_glass_doors:oak_glass_door (from fabric), modern_glass_doors:spruce_glass_door (from fabric), modern_glass_doors:birch_glass_door (from fabric), modern_glass_doors:acacia_glass_door (from fabric), modern_glass_doors:jungle_glass_door (from fabric), modern_glass_doors:dark_oak_glass_door (from fabric), modern_glass_doors:crimson_glass_door (from fabric), modern_glass_doors:warped_glass_door (from fabric), modern_glass_doors:mangrove_glass_door (from fabric), modern_glass_doors:bamboo_glass_door (from fabric), modern_glass_doors:cherry_glass_door (from fabric)
...
```
And a JSON error
```
[19:22:14] [Worker-Main-2/ERROR]: Couldn't parse element loot_tables:modern_glass_doors:blocks/jungle_glass_trapdoor
com.google.gson.JsonSyntaxException: Expected name to be an item, was unknown string 'modern_glass_doors:jungle_glass_trapdoor'
	at net.minecraft.class_3518.method_17995(class_3518.java:145) ~[server-intermediary.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.class_3518.method_15256(class_3518.java:145) ~[server-intermediary.jar:?]
	at net.minecraft.class_3518.method_15288(class_3518.java:153) ~[server-intermediary.jar:?]
	at net.minecraft.class_77$class_78.method_413(class_77.java:55) ~[server-intermediary.jar:?]
	at net.minecraft.class_77$class_78.method_443(class_77.java:40) ~[server-intermediary.jar:?]
	at net.minecraft.class_85$class_90.method_441(class_85.java:151) ~[server-intermediary.jar:?]
	at net.minecraft.class_85$class_90.method_424(class_85.java:129) ~[server-intermediary.jar:?]
	at net.minecraft.class_79$class_5337.method_29319(class_79.java:86) ~[server-intermediary.jar:?]
	at net.minecraft.class_79$class_5337.method_517(class_79.java:74) ~[server-intermediary.jar:?]
	at net.minecraft.class_5330$class_5333.deserialize(class_5330.java:102) ~[server-intermediary.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1290) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179) ~[gson-2.10.jar:?]
	at net.minecraft.class_3518.method_15291(class_3518.java:463) ~[server-intermediary.jar:?]
	at net.minecraft.class_3518.method_15272(class_3518.java:471) ~[server-intermediary.jar:?]
	at net.minecraft.class_55$class_57.method_358(class_55.java:173) ~[server-intermediary.jar:?]
	at net.minecraft.class_55$class_57.deserialize(class_55.java:169) ~[server-intermediary.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1290) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179) ~[gson-2.10.jar:?]
	at net.minecraft.class_3518.method_15291(class_3518.java:463) ~[server-intermediary.jar:?]
	at net.minecraft.class_3518.method_15283(class_3518.java:481) ~[server-intermediary.jar:?]
	at net.minecraft.class_52$class_54.method_340(class_52.java:250) ~[server-intermediary.jar:?]
	at net.minecraft.class_52$class_54.deserialize(class_52.java:246) ~[server-intermediary.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1261) ~[gson-2.10.jar:?]
	at net.minecraft.class_8490.method_51205(class_8490.java:64) ~[server-intermediary.jar:?]
	at net.minecraft.class_8490.method_51204(class_8490.java:48) ~[server-intermediary.jar:?]
	at net.minecraft.class_60.method_51195(class_60.java:55) ~[server-intermediary.jar:?]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at net.minecraft.class_60.method_51189(class_60.java:55) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
```
The complete log is [here](https://gist.github.com/vico93/949e795e2aaab1d1fd80b47a2fc1fd01).

**Comment by vico93** [comment]
Well, seems like this and #18 are related... basically i think the whole datapack part of the mod is broken and is disabling the rest of the vanilla and other mods tag system - I had the some problem of that issue and after following @AkashiiKun advice to use LMFT it fix the issue, abeit warning of the tag issues. I never followed the issue until today when i realized the whole errors shown above. I hope you guys fix that.
